name: Build and Deploy Windows Executable


#on:
  #schedule:
   # - cron: '0 18 * * *' #早上2点
  #push:
    #branches:
      #- main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pyinstaller selenium requests futures eventlet

      - name: Build executable
        run: pyinstaller IPTV-hebei.py --onefile --hidden-import=eventlet.hubs.epolls --hidden-import=eventlet.hubs.kqueue --hidden-import=eventlet.hubs.selects --hidden-import=dns --hidden-import=dns.rdtypes --hidden-import=dns.rdtypes.ANY --hidden-import=dns.rdtypes.IN --hidden-import=dns.rdtypes.CH --hidden-import=dns.rdtypes.dnskeybase --hidden-import=dns.asyncbackend --hidden-import=dns.asyncquery --hidden-import=dns.asyncresolver --hidden-import=dns.dnssec --hidden-import=dns.e164 --hidden-import=dns.namedict --hidden-import=dns.tsigkeyring --hidden-import=dns.versioned
      - run: pyinstaller windows_test.py --onefile	
      #- name: Create directory
      #  run: mkdir -p windows
      - name: Remove existing file
        run: rm windows/IPTV-hebei.exe
      - run: rm windows/windows_test.exe

      - name: Move executable to directory
        run: mv dist/IPTV-hebei.exe windows/
      - run: mv dist/windows_test.exe windows/

      - name: 提交更改
        run: |
          git config --global user.name "ssili126"
          git config --global user.email "ssili@126.com"
          git add windows/IPTV-hebei.exe
          git add windows/windows_test.exe
          git commit -m "Update Windows executable"
          git push
